
import { LanguageCode } from './types';

export const translations = {
  en: {
    appName: "Wuyiyit (Dialogue) AI",
    loginPrompt: "Please sign in or sign up to continue.",
    signInWithEmail: "Sign In with Email",
    signUpWithEmail: "Sign Up with Email",
    nameLabel: "Name",
    namePlaceholder: "Enter your full name",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirm Password",
    signInButton: "Sign In",
    signUpButton: "Sign Up",
    switchToSignUp: "Don't have an account? Sign Up",
    switchToSignIn: "Already have an account? Sign In",
    backToMainLogin: "Back to main login options",
    nameRequiredError: "Name is required.",
    passwordMismatchError: "Passwords do not match.",
    passwordLengthError: "Password must be at least 6 characters.",
    incorrectPasswordError: "Incorrect password.",
    emailNotRegisteredError: "Email not registered. Please sign up.",
    emailRegisteredError: "Email already registered. Please log in.",
    loginFailedError: "Login failed: ",
    signUpFailedError: "Sign up failed: ",
    copyright: `© ${new Date().getFullYear()} Wuyiyit AI`,
    loading: "Loading...",
    loadingChatData: "Loading chat data...",
    loadingMessages: "Loading messages for this chat...", 
    apiKeyMissing: "API_KEY environment variable not found. Please set it to use the chatbot.",
    dbAccessDeniedError: "Database access denied by security policies (RLS Error {code}). Please check Supabase Row Level Security policies for table '{table}'. Ensure the 'anon' role (due to custom auth bypass) has appropriate SELECT/INSERT/UPDATE/DELETE permissions.",
    dbTimeoutError: "Loading data for {context} took too long and timed out. Please try again. If the problem persists, the chat session might contain a very large number of messages.",
    operationFailedError: "Operation failed ({context}): {message}",
    pleaseLoginToChat: "Please log in to start a new chat.",
    newChat: "New Chat",
    noChatSessions: "No chat sessions yet. Click \"New Chat\" to start.",
    pleaseLoginToViewChats: "Please log in to view chats.",
    loggedInAs: "Logged in:",
    logout: "Logout",
    help: "Help",
    deleteChat: "Delete chat {sessionName}",
    confirmDeleteTitle: "Confirm Delete",
    confirmDeleteMessage: "Are you sure you want to permanently delete \"{sessionName}\"? This action cannot be undone.",
    cancel: "Cancel",
    yesDelete: "Yes, Delete",
    // clearHistoryTitle: "Clear History?", // Removed
    // clearHistoryMessage: "Are you sure you want to clear all history for this chat? This action cannot be undone. The chat session itself will remain.", // Removed
    // yesClear: "Yes, Clear", // Removed
    switchToDarkMode: "Switch to dark mode",
    switchToLightMode: "Switch to light mode",
    toggleChatSessions: "Toggle chat sessions",
    startNewChatPrompt: "Create a new chat or select an existing one to begin.",
    howCanIHelp: "How can I help you?",
    typeMessageOrAttachFile: "Type your message, or attach a file, then press Enter or Send.",
    medicalModeDisclaimer: "Attention: This AI does not provide medical advice. The information is for educational purposes only. Consult a healthcare professional for health concerns.",
    unsupportedFileType: "Unsupported file type. Please upload {fileTypes}.",
    fileTooLarge: "File is too large. Maximum size is {maxSize}MB.",
    imagePreviewError: "Could not display image preview.",
    fileProcessingError: "Could not process the attached file.",
    aiResponseError: "Could not get a response from AI: {errorMessage}.",
    aiRegionError: "Sorry, this service is not yet available in your region.",
    aiBillingError: "There seems to be a billing issue with your API key. Please check.",
    chatInputPlaceholder: "Enter your message or attach a file...",
    chatInputSelectSessionPlaceholder: "Select a chat or start a new one...",
    chatInputApiKeyNeededPlaceholder: "API Key required...",
    attachFile: "Attach file",
    sendMessage: "Send message",
    generalMode: "General",
    medicalMode: "Medical",
    childMode: "Child",
    studentMode: "Student",
    installApp: "Install App",
    installManuallyHelp: "To install, open your browser's menu and look for 'Add to Home Screen' or 'Install app'.",
    // Help Modal Content
    helpModalTitle: "Welcome to Wuyiyit AI!",
    helpModalHowToUse: "How to Use:",
    helpModalNewChat: "To start a new chat: Click the \"New Chat\" button on the left.",
    helpModalSendMessage: "Sending messages: Type your message in the text box at the bottom and press Enter or click Send (paper airplane icon).",
    helpModalAttachFile: "Attaching files (📎): Click the paperclip icon. You can attach images (JPG, PNG, etc.) or PDF files (up to 4MB).",
    helpModalChatModes: "Selecting chat modes: Use the mode selection chips above the message input:",
    helpModalModeGeneral: "General: For common and general questions.",
    helpModalModeMedical: "Medical: For medical information (Attention: This is not a substitute for professional advice!).",
    helpModalModeChild: "Child: Simple, kid-friendly responses with emojis, suitable for users under 13.",
    helpModalModeStudent: "Student: Detailed explanations and knowledge for high school students.",
    helpModalSwitchChats: "Switching chats: Click on a chat session from the list on the left to select it.",
    helpModalDeleteChat: "Deleting a chat (🗑️): Click the trash icon next to each chat name to delete the entire chat.",
    // helpModalClearHistory: "Clearing chat history (🧹): Click the broom icon at the top right of the chat area to clear all messages for the current chat. The chat session itself will remain but empty.", // Removed
    helpModalAiResponses: "AI Responses:",
    helpModalAiAmharicOnly: "Wuyiyit AI will always provide its responses entirely in Amharic. It may use different headings and text formats (Markdown) to make responses clear and readable.",
    helpModalDevInfo: "Developed by: Bereket Afework",
    helpModalContact: "Contact: +251931555192",
    helpModalEnjoy: "Enjoy your chat!",
    error: "Error",
  },
  am: {
    appName: "ውይይት AI",
    loginPrompt: "ለመቀጠል እባክዎ ይግቡ ወይም ይመዝገቡ።",
    signInWithEmail: "በኢሜይል ይግቡ",
    signUpWithEmail: "በኢሜይል ይመዝገቡ",
    nameLabel: "ስም",
    namePlaceholder: "ሙሉ ስም ያስገቡ",
    emailLabel: "ኢሜይል",
    emailPlaceholder: "you@example.com",
    passwordLabel: "የይለፍ ቃል",
    passwordPlaceholder: "••••••••",
    confirmPasswordLabel: "የይለፍ ቃል ያረጋግጡ",
    signInButton: "ይግቡ",
    signUpButton: "ይመዝገቡ",
    switchToSignUp: "አካውንት የለዎትም? ይመዝገቡ",
    switchToSignIn: "አካውንት አለዎት? ይግቡ",
    backToMainLogin: "ወደ ዋናው የመግቢያ ገጽ ይመለሱ",
    nameRequiredError: "ስም ማስገባት ግዴታ ነው።",
    passwordMismatchError: "የይለፍ ቃሎች አይዛመዱም።",
    passwordLengthError: "የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት።",
    incorrectPasswordError: "የይለፍ ቃል ትክክል አይደለም።",
    emailNotRegisteredError: "ይህ ኢሜይል አልተመዘገበም። እባክዎ ይመዝገቡ።",
    emailRegisteredError: "ይህ ኢሜይል አስቀድሞ ተመዝግቧል። እባክዎ ይግቡ።",
    loginFailedError: "መግባት አልተሳካም፦ ",
    signUpFailedError: "መመዝገብ አልተሳካም፦ ",
    copyright: `© ${new Date().getFullYear()} ውይይት AI`,
    loading: "በመጫን ላይ...",
    loadingChatData: "የውይይት መረጃ በመጫን ላይ...",
    loadingMessages: "የዚህን ውይይት መልዕክቶች በመጫን ላይ...", 
    apiKeyMissing: "እባክዎ ይህን መተግበሪያ ለመጠቀም የ API_KEY ኢንቫይሮመንት ተለዋዋጭ ያዘጋጁ።",
    dbAccessDeniedError: "የውሂብ ጎታ መዳረሻ በደህንነት ፖሊሲዎች ተከልክሏል (RLS Error {code})። እባክዎ የ Supabase Row Level Security ፖሊሲዎችን ለ '{table}' ሰንጠረዥ ያረጋግጡ። የ 'anon' ሚና (በብጁ ማረጋገጫ ምክንያት) ተገቢውን የ SELECT/INSERT/UPDATE/DELETE መብቶች እንዳገኘ ያረጋግጡ።",
    dbTimeoutError: "ለ {context} መረጃ መጫን በጣም ረጅም ጊዜ ስለፈጀ ጊዜው አልቋል። እባክዎ እንደገና ይሞክሩ። ችግሩ ከቀጠለ፣ የውይይት ክፍለ-ጊዜው በጣም ብዙ መልዕክቶችን የያዘ ሊሆን ይችላል።",
    operationFailedError: "ኦፕሬሽን አልተሳካም ({context})፦ {message}",
    pleaseLoginToChat: "እባክዎ አዲስ ውይይት ከመጀመርዎ በፊት ይግቡ።",
    newChat: "New Chat", 
    noChatSessions: "እስካሁን ምንም የውይይት ክፍለ ጊዜ የለም። አዲስ ለመጀመር \"New Chat\" የሚለውን ይጫኑ።",
    pleaseLoginToViewChats: "እባክዎ ውይይቶችን ለማየት ይግቡ።",
    loggedInAs: "የገቡት አካውንት:",
    logout: "ውጣ",
    help: "እገዛ",
    deleteChat: "ውይይት ይሰረዝ {sessionName}",
    confirmDeleteTitle: "ውይይት ይሰረዝ?",
    confirmDeleteMessage: "\"{sessionName}\" በቋሚነት ሊሰርዙት ነው? ይህ ድርጊት መመለስ አይቻልም።",
    cancel: "ይቅር",
    yesDelete: "አዎ፣ ይሰረዝ",
    // clearHistoryTitle: "ታሪክ ይጽዳ?", // Removed
    // clearHistoryMessage: "የዚህን ውይይት ታሪክ በሙሉ ማጽዳት ይፈልጋሉ? ይህ ድርጊት መመለስ አይቻልም። ውይይቱ ራሱ ግን ይቀራል።", // Removed
    // yesClear: "አዎ፣ ይጽዳ", // Removed
    switchToDarkMode: "ወደ ጨለማ ገጽታ ቀይር",
    switchToLightMode: "ወደ ብሩህ ገጽታ ቀይር",
    toggleChatSessions: "የውይይት ዝርዝር ክፈት/ዝጋ",
    startNewChatPrompt: "ለመጀመር አዲስ ውይይት ይፍጠሩ ወይም ያለውን ይምረጡ።",
    howCanIHelp: "እንዴት ልረዳዎ እችላለሁ?",
    typeMessageOrAttachFile: "መልዕክትዎን ይጻፉ፣ ወይም ፋይል ያያይዙ፣ ከዚያ Enter ይጫኑ ወይም ላክ የሚለውን ይጫኑ።",
    medicalModeDisclaimer: "ትኩረት: ይህ AI የሕክምና ምክር አይሰጥም። መረጃው ለመማሪያ ብቻ ነው። የጤና ችግር ካለብዎ የጤና ባለሙያ ያማክሩ።",
    unsupportedFileType: "የማይደገፍ የፋይል አይነት። እባክዎ {fileTypes} ይጫኑ።",
    fileTooLarge: "ፋይሉ በጣም ትልቅ ነው። ከፍተኛው መጠን {maxSize}MB ነው።",
    imagePreviewError: "ምስሉን ማሳየት አልተቻለም።",
    fileProcessingError: "የተያያዘውን ፋይል ማዘጋጀት አልተቻለም።",
    aiResponseError: "ከ AI ምላሽ ማግኘት አልተቻለም: {errorMessage}.",
    aiRegionError: "ይቅርታ፣ በአካባቢዎ ይህ አገልግሎት ገና አልተፈቀደም።",
    aiBillingError: "የኤፒአይ ቁልፍዎ ላይ የክፍያ ችግር ያለ ይመስላል። እባክዎ ያረጋግጡ።",
    chatInputPlaceholder: "መልዕክትዎን ያስገቡ ወይም ፋይል ያያይዙ...",
    chatInputSelectSessionPlaceholder: "ውይይት ይምረጡ ወይም አዲስ ይጀምሩ...",
    chatInputApiKeyNeededPlaceholder: "የኤፒአይ ቁልፍ ያስፈልጋል...",
    attachFile: "ፋይል አያይዝ",
    sendMessage: "ላክ",
    generalMode: "አጠቃላይ",
    medicalMode: "ሕክምና",
    childMode: "ልጅ",
    studentMode: "ተማሪ",
    installApp: "መተግበሪያ ጫን",
    installManuallyHelp: "ለመጫን፣ የአሳሽዎን ምናሌ ይክፈቱ እና 'ወደ መነሻ ገጽ አክል' ወይም 'መተግበሪያ ጫን' የሚለውን ይፈልጉ።",
    // Help Modal Content
    helpModalTitle: "እንኳን ወደ ውይይት AI በደህና መጡ!",
    helpModalHowToUse: "እንዴት መጠቀም እንደሚቻል:",
    helpModalNewChat: "አዲስ ውይይት ለመጀመር: በግራ በኩል ያለውን \"New Chat\" የሚለውን ቁልፍ ይጫኑ።",
    helpModalSendMessage: "መልዕክት መላክ: መልዕክትዎን ከታች ባለው የጽሑፍ ሳጥን ውስጥ ይጻፉና Enter ወይም ላክ (የወረቀት አውሮፕላን ምልክት) የሚለውን ይጫኑ።",
    helpModalAttachFile: "ፋይል ማያያዝ (📎): የወረቀት ክሊፕ ምልክቱን ይጫኑ። ምስሎችን (JPG, PNG, ወዘተ) ወይም PDF ፋይሎችን (እስከ 4MB) ማያያዝ ይችላሉ።",
    helpModalChatModes: "የውይይት አይነት መምረጥ: ከመልዕክት መጻፊያው በላይ ያሉትን የአይነት መምረጫዎች (ቺፖችን) ይጠቀሙ፦",
    helpModalModeGeneral: "General (አጠቃላይ): ለተለመዱ እና አጠቃላይ ጥያቄዎች።",
    helpModalModeMedical: "Medical (ሕክምና): ለሕክምና ነክ መረጃዎች (ትኩረት፦ ይህ የባለሙያ ምክርን አይተካም!)።",
    helpModalModeChild: "Child (ልጅ): ለሕጻናት (ከ13 ዓመት በታች) ተስማሚ የሆኑ ቀላል ምላሾች ከኢሞጂ ጋር።",
    helpModalModeStudent: "Student (ተማሪ): ለሁለተኛ ደረጃ ተማሪዎች ዝርዝር ማብራሪያዎች እና ዕውቀት።",
    helpModalSwitchChats: "ውይይቶችን መቀያየር: በግራ በኩል ካሉት የውይይት ዝርዝሮች ውስጥ የሚፈልጉትን በመጫን መምረጥ ይችላሉ።",
    helpModalDeleteChat: "ውይይት መሰረዝ (🗑️): ከእያንዳንዱ የውይይት ስም ጎን የሚገኘውን የመሰረዣ ምልክት በመጫን ሙሉ ውይይቱን መሰረዝ ይችላሉ።",
    // helpModalClearHistory: "የውይይት ታሪክ ማጽዳት (🧹): የአሁኑን ውይይት መልዕክቶች በሙሉ ለማጽዳት ከላይ በቀኝ በኩል ያለውን የማጽጃ ምልክት ይጫኑ። ውይይቱ ራሱ ባዶ ሆኖ ይቀራል።", // Removed
    helpModalAiResponses: "የ AI ምላሾች:",
    helpModalAiAmharicOnly: "ውይይት AI ሁልጊዜ ምላሾቹን በሙሉ በአማርኛ ብቻ ይሰጣል። ምላሾቹ ግልጽ እና ለማንበብ ቀላል እንዲሆኑ የተለያዩ ርዕሶችን እና የጽሑፍ ቅርጸቶችን (Markdown) ሊጠቀሙ ይችላሉ።",
    helpModalDevInfo: "የተሰራው በ: በረከት አፈወርቅ",
    helpModalContact: "ስልክ: +251931555192",
    helpModalEnjoy: "መልካም ውይይት!",
    error: "ስህተት",
  },
};

export type TranslationKey = keyof typeof translations.en; // Or keyof typeof translations.am

export const t = (lang: LanguageCode, key: TranslationKey, replacements?: Record<string, string | number>): string => {
  let translation = translations[lang]?.[key] || translations.en[key] || key;
  if (replacements) {
    Object.keys(replacements).forEach(rKey => {
      translation = translation.replace(`{${rKey}}`, String(replacements[rKey]));
    });
  }
  return translation;
};